package ar.edu.unlam.pb2;

public enum MenuPrincipal {
	AGREGAR_PROPIEDAD,
	MODIFICAR_PROPIEDAD,
	AGREGAR_CLIENTE,
	LISTADO_PROPIEDADES_ORDENADO_POR_PRECIO,
	LISTADO_PROPIEDADES_ORDENADO_POR_UBICACION,
	BUSCAR_PROPIEDAD_POR_DIFERENTES_PARAMETROS,
	REALIZAR_VENTA,
	REALIZAR_ALQUILER,
	SALIR
}
